local removed_pipes = {
  "reinforced-pipe-rampant-arsenal",
  "reinforced-pipe-to-ground-rampant-arsenal",
}
local removed_recipes = {
  "reinforced-pipe-rampant-arsenal",
  "reinforced-pipe-to-ground-rampant-arsenal",
  -- Auto-generated by the recycler feature for each removed pipe; these only
  -- exist against the real published RampantArsenalFork, not the local
  -- fixture below, which is why this fixture is what caught the gap.
  "reinforced-pipe-rampant-arsenal-recycling",
  "reinforced-pipe-to-ground-rampant-arsenal-recycling",
  -- Simulated by the local RampantArsenalFork fixture (tests/fixtures/RampantArsenalFork)
  -- to exercise positional/keyed/single-result ingredient matching; these
  -- never exist against the real mod, so they trivially pass there.
  "rampant-arsenal-recycling-positional-ingredient",
  "rampant-arsenal-recycling-keyed-result",
  "rampant-arsenal-recycling-single-result",
}
local removed_recipe_names = {}
for _, name in pairs(removed_recipes) do
  removed_recipe_names[name] = true
end

for _, name in pairs(removed_pipes) do
  assert(not data.raw.pipe[name], name .. " pipe prototype was not removed")
  assert(not data.raw["pipe-to-ground"][name], name .. " pipe-to-ground prototype was not removed")
  assert(not data.raw.item[name], name .. " item prototype was not removed")
end

for _, name in pairs(removed_recipes) do
  assert(not data.raw.recipe[name], name .. " recipe was not removed")
end

assert(
  not data.raw.technology["rampant-arsenal-technology-reinforced-pipes"],
  "Rampant Arsenal reinforced pipe technology was not removed"
)

-- Scan every technology (not just one assumed name) for a dangling
-- unlock-recipe effect pointing at any removed recipe. The vanilla
-- "recycling" technology is the real-world case this exists to catch: the
-- recycler feature adds unlock-recipe effects to it for auto-generated
-- recycling recipes, and those effects must not outlive the recipe removal.
for _, technology in pairs(data.raw.technology or {}) do
  for _, effect in pairs(technology.effects or {}) do
    if effect.type == "unlock-recipe" then
      assert(
        not removed_recipe_names[effect.recipe],
        "technology " .. technology.name .. " still unlocks removed recipe " .. tostring(effect.recipe)
      )
    end
  end
end
